# Gradle properties

quarkusPluginId=io.quarkus
quarkusPluginVersion=3.37.4
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.37.4

org.gradle.logging.stacktrace=all
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.configuration-cache.problems=warn